import type { CrmData, MerchantStatus } from "@/lib/types";
import { calculatePersonalResidual, requiresManagementApproval } from "@/lib/compensation";
import { defaultRolePermissions, enterpriseSettingDefaults } from "@/lib/permissions";

const now = "2026-05-06T12:00:00.000Z";

export const pipelineStages: { id: MerchantStatus; label: string }[] = [
  { id: "lead", label: "New Lead" },
  { id: "contacted", label: "Contacted" },
  { id: "qualified", label: "Qualified" },
  { id: "application_sent", label: "Application Sent" },
  { id: "underwriting", label: "Underwriting" },
  { id: "approved", label: "Approved" },
  { id: "onboarded", label: "Onboarded" },
  { id: "processing", label: "Processing" },
  { id: "lost", label: "Lost" },
];

export const demoData: CrmData = {
  profiles: [
    {
      id: "profile-admin",
      user_id: "user-admin",
      full_name: "Maya Chen",
      email: "maya@merchantdesk.example",
      role: "admin",
      phone: "(716) 555-0110",
      status: "active",
      manager_id: null,
      created_at: now,
    },
    {
      id: "profile-manager",
      user_id: "user-manager",
      full_name: "Andre Blake",
      email: "andre@merchantdesk.example",
      role: "manager",
      phone: "(716) 555-0111",
      status: "active",
      manager_id: null,
      created_at: now,
    },
    {
      id: "profile-agent-1",
      user_id: "user-agent-1",
      full_name: "Jordan Ellis",
      email: "jordan@merchantdesk.example",
      role: "agent",
      phone: "(716) 555-0112",
      status: "active",
      manager_id: "profile-manager",
      created_at: now,
    },
    {
      id: "profile-agent-2",
      user_id: "user-agent-2",
      full_name: "Priya Singh",
      email: "priya@merchantdesk.example",
      role: "agent",
      phone: "(716) 555-0113",
      status: "active",
      manager_id: "profile-manager",
      created_at: now,
    },
    {
      id: "profile-agent-3",
      user_id: "user-agent-3",
      full_name: "Marcus Reed",
      email: "marcus@merchantdesk.example",
      role: "agent",
      phone: "(716) 555-0114",
      status: "active",
      manager_id: "profile-manager",
      created_at: now,
    },
  ],
  agents: [
    {
      id: "agent-1",
      profile_id: "profile-agent-1",
      agent_code: "CV-JE-001",
      sponsor_agent_id: null,
      team_number: 1,
      team_position: 1,
      status: "active",
      start_date: "2025-01-05",
      created_at: now,
    },
    {
      id: "agent-2",
      profile_id: "profile-agent-2",
      agent_code: "CV-PS-002",
      sponsor_agent_id: "agent-1",
      team_number: 1,
      team_position: 2,
      status: "active",
      start_date: "2025-07-18",
      created_at: now,
    },
    {
      id: "agent-3",
      profile_id: "profile-agent-3",
      agent_code: "CV-MR-003",
      sponsor_agent_id: "agent-1",
      team_number: 1,
      team_position: 3,
      status: "ramping",
      start_date: "2026-02-14",
      created_at: now,
    },
  ],
  merchants: [
    {
      id: "merchant-1",
      business_name: "Joe's Pizza Works",
      contact_name: "Mike Romano",
      contact_email: "mike@joespizza.example",
      contact_phone: "(716) 555-0191",
      business_address: "210 Elmwood Ave, Buffalo, NY",
      industry: "Restaurant",
      monthly_volume_estimate: 45000,
      average_ticket: 28,
      current_processor: "Fiserv",
      proposed_rate: 1.72,
      status: "qualified",
      assigned_agent_id: "agent-1",
      processing_start_date: null,
      is_verified: false,
      notes: "Owner wants transparent pricing and fast deposit timing.",
      created_at: "2026-04-18T10:00:00.000Z",
      updated_at: "2026-05-03T11:00:00.000Z",
    },
    {
      id: "merchant-2",
      business_name: "Buffalo Auto Detail",
      contact_name: "Sarah Mills",
      contact_email: "sarah@buffaloauto.example",
      contact_phone: "(716) 555-0139",
      business_address: "88 Seneca St, Buffalo, NY",
      industry: "Auto Services",
      monthly_volume_estimate: 62000,
      average_ticket: 185,
      current_processor: "Square",
      proposed_rate: 1.44,
      status: "underwriting",
      assigned_agent_id: "agent-1",
      processing_start_date: null,
      is_verified: false,
      notes: "High-value deal below floor. Manager review required.",
      created_at: "2026-04-11T10:00:00.000Z",
      updated_at: "2026-04-26T15:20:00.000Z",
    },
    {
      id: "merchant-3",
      business_name: "Queen City Dental",
      contact_name: "Dr. Alicia Warren",
      contact_email: "ops@qcdental.example",
      contact_phone: "(716) 555-0188",
      business_address: "1120 Delaware Ave, Buffalo, NY",
      industry: "Healthcare",
      monthly_volume_estimate: 128000,
      average_ticket: 420,
      current_processor: "Elavon",
      proposed_rate: 1.86,
      status: "processing",
      assigned_agent_id: "agent-1",
      processing_start_date: "2025-11-01",
      is_verified: true,
      notes: "Stable processor, excellent residual anchor account.",
      created_at: "2025-09-21T10:00:00.000Z",
      updated_at: "2026-05-01T09:30:00.000Z",
    },
    {
      id: "merchant-4",
      business_name: "Northside Fitness",
      contact_name: "Tanya Bell",
      contact_email: "tanya@northfit.example",
      contact_phone: "(716) 555-0162",
      business_address: "350 Hertel Ave, Buffalo, NY",
      industry: "Fitness",
      monthly_volume_estimate: 82000,
      average_ticket: 74,
      current_processor: "Stripe",
      proposed_rate: 1.67,
      status: "approved",
      assigned_agent_id: "agent-2",
      processing_start_date: null,
      is_verified: false,
      notes: "Approved, needs equipment deployment date.",
      created_at: "2026-03-17T10:00:00.000Z",
      updated_at: "2026-04-29T09:00:00.000Z",
    },
    {
      id: "merchant-5",
      business_name: "Canalside Market",
      contact_name: "Owen Patel",
      contact_email: "owen@canalsidemarket.example",
      contact_phone: "(716) 555-0134",
      business_address: "44 Marine Dr, Buffalo, NY",
      industry: "Retail",
      monthly_volume_estimate: 94000,
      average_ticket: 52,
      current_processor: "Fiserv",
      proposed_rate: 1.79,
      status: "processing",
      assigned_agent_id: "agent-2",
      processing_start_date: "2025-10-03",
      is_verified: true,
      notes: "Eligible merchant for recruit activation.",
      created_at: "2025-08-09T10:00:00.000Z",
      updated_at: "2026-04-20T13:00:00.000Z",
    },
    {
      id: "merchant-6",
      business_name: "Elm Street Books",
      contact_name: "Nora Collins",
      contact_email: "nora@elmbooks.example",
      contact_phone: "(716) 555-0119",
      business_address: "9 Elm St, Buffalo, NY",
      industry: "Retail",
      monthly_volume_estimate: 36000,
      average_ticket: 33,
      current_processor: "Clover",
      proposed_rate: 1.62,
      status: "contacted",
      assigned_agent_id: "agent-3",
      processing_start_date: null,
      is_verified: false,
      notes: "Needs follow-up after weekend event.",
      created_at: "2026-04-02T10:00:00.000Z",
      updated_at: "2026-04-19T13:00:00.000Z",
    },
  ],
  deals: [],
  merchantUpdates: [
    {
      id: "update-1",
      merchant_id: "merchant-1",
      agent_id: "agent-1",
      update_type: "call",
      note: "Mike wants a follow-up Friday and confirmed roughly $45k/month in card volume.",
      next_follow_up_date: "2026-05-08T14:00:00.000Z",
      created_at: "2026-05-03T11:00:00.000Z",
    },
    {
      id: "update-2",
      merchant_id: "merchant-2",
      agent_id: "agent-1",
      update_type: "pricing",
      note: "Pricing exception submitted for management approval.",
      next_follow_up_date: "2026-05-06T16:00:00.000Z",
      created_at: "2026-04-26T15:20:00.000Z",
    },
    {
      id: "update-3",
      merchant_id: "merchant-6",
      agent_id: "agent-3",
      update_type: "email",
      note: "Sent comparison quote. No update in 17 days.",
      next_follow_up_date: "2026-05-06T10:00:00.000Z",
      created_at: "2026-04-19T13:00:00.000Z",
    },
  ],
  tasks: [
    {
      id: "task-1",
      title: "Follow up with Joe's Pizza",
      description: "Ask Mike for statements and confirm desired equipment.",
      assigned_to: "profile-agent-1",
      merchant_id: "merchant-1",
      due_date: "2026-05-08T14:00:00.000Z",
      priority: "high",
      status: "open",
      created_at: now,
    },
    {
      id: "task-2",
      title: "Manager review for Buffalo Auto Detail",
      description: "Approve or revise 1.44% proposed rate.",
      assigned_to: "profile-manager",
      merchant_id: "merchant-2",
      due_date: "2026-05-06T16:00:00.000Z",
      priority: "high",
      status: "open",
      created_at: now,
    },
    {
      id: "task-3",
      title: "Call Elm Street Books",
      description: "Lead is stale and quote is outstanding.",
      assigned_to: "profile-agent-3",
      merchant_id: "merchant-6",
      due_date: "2026-05-06T10:00:00.000Z",
      priority: "medium",
      status: "overdue",
      created_at: now,
    },
  ],
  documents: [
    {
      id: "document-1",
      merchant_id: "merchant-3",
      uploaded_by: "agent-1",
      file_name: "queen-city-dental-statements.pdf",
      file_url: "/documents/demo.pdf",
      document_type: "Processing statements",
      created_at: "2026-04-05T10:00:00.000Z",
    },
  ],
  agentRecruits: [
    {
      id: "recruit-1",
      full_name: "Taylor Morgan",
      email: "taylor@agentcandidate.example",
      phone: "(716) 555-0201",
      source: "Referral",
      status: "interested",
      assigned_recruiter_id: "profile-agent-1",
      created_by: "profile-agent-1",
      follow_up_at: "2026-05-16T14:00:00.000Z",
      notes: "Experienced in restaurant POS sales. Wants override details.",
      created_at: "2026-05-01T14:00:00.000Z",
      updated_at: "2026-05-06T14:00:00.000Z",
    },
    {
      id: "recruit-2",
      full_name: "Sam Rivera",
      email: "sam@agentcandidate.example",
      phone: "(716) 555-0202",
      source: "LinkedIn",
      status: "application_started",
      assigned_recruiter_id: "profile-agent-2",
      created_by: "profile-manager",
      follow_up_at: "2026-05-19T15:30:00.000Z",
      notes: "Submitted initial questionnaire and needs agreement review.",
      created_at: "2026-04-26T14:00:00.000Z",
      updated_at: "2026-05-05T11:00:00.000Z",
    },
  ],
  agentRecruitUpdates: [
    {
      id: "recruit-update-1",
      recruit_id: "recruit-1",
      author_profile_id: "profile-agent-1",
      status: "interested",
      note: "Reviewed income goals and explained merchant activation requirements.",
      follow_up_at: "2026-05-16T14:00:00.000Z",
      created_at: "2026-05-06T14:00:00.000Z",
    },
    {
      id: "recruit-update-2",
      recruit_id: "recruit-2",
      author_profile_id: "profile-manager",
      status: "application_started",
      note: "Application started; waiting on signed agent agreement.",
      follow_up_at: "2026-05-19T15:30:00.000Z",
      created_at: "2026-05-05T11:00:00.000Z",
    },
  ],
  agentOnboardingRecords: [
    {
      id: "agent-onboarding-1",
      profile_id: null,
      recruit_id: "recruit-2",
      full_name: "Sam Rivera",
      email: "sam@agentcandidate.example",
      phone: "(716) 555-0202",
      assigned_admin_id: "profile-admin",
      status: "documents_pending",
      profile_complete: true,
      training_progress: 50,
      documents_signed: false,
      account_activated: false,
      admin_approved_at: null,
      created_at: "2026-05-05T12:00:00.000Z",
      updated_at: "2026-05-06T12:00:00.000Z",
    },
  ],
  agentOnboardingSteps: [
    {
      id: "agent-onboarding-step-1",
      onboarding_id: "agent-onboarding-1",
      title: "Complete agent profile",
      description: null,
      step_order: 1,
      completed_at: "2026-05-05T14:00:00.000Z",
      created_at: "2026-05-05T12:00:00.000Z",
    },
    {
      id: "agent-onboarding-step-2",
      onboarding_id: "agent-onboarding-1",
      title: "Review merchant processing training",
      description: null,
      step_order: 2,
      completed_at: "2026-05-06T10:00:00.000Z",
      created_at: "2026-05-05T12:00:00.000Z",
    },
    {
      id: "agent-onboarding-step-3",
      onboarding_id: "agent-onboarding-1",
      title: "Sign agent agreement",
      description: null,
      step_order: 3,
      completed_at: null,
      created_at: "2026-05-05T12:00:00.000Z",
    },
  ],
  merchantOnboardingRecords: [
    {
      id: "merchant-onboarding-1",
      merchant_id: "merchant-2",
      business_name: "Buffalo Auto Detail",
      contact_name: "Sarah Mills",
      contact_email: "sarah@buffaloauto.example",
      contact_phone: "(716) 555-0139",
      industry: "Auto Services",
      processing_needs: "Needs card-present, invoicing, and next-day funding comparison.",
      monthly_volume_estimate: 62000,
      average_ticket: 185,
      current_processor: "Square",
      status: "under_review",
      assigned_agent_id: "agent-1",
      follow_up_at: "2026-05-15T16:00:00.000Z",
      notes: "Manager pricing review is still pending.",
      created_at: "2026-05-02T12:00:00.000Z",
      updated_at: "2026-05-06T12:00:00.000Z",
    },
  ],
  merchantOnboardingSteps: [
    {
      id: "merchant-onboarding-step-1",
      onboarding_id: "merchant-onboarding-1",
      title: "Capture business and ownership details",
      description: null,
      step_order: 1,
      completed_at: "2026-05-03T12:00:00.000Z",
      created_at: "2026-05-02T12:00:00.000Z",
    },
    {
      id: "merchant-onboarding-step-2",
      onboarding_id: "merchant-onboarding-1",
      title: "Confirm processing needs",
      description: null,
      step_order: 2,
      completed_at: "2026-05-03T13:00:00.000Z",
      created_at: "2026-05-02T12:00:00.000Z",
    },
    {
      id: "merchant-onboarding-step-3",
      onboarding_id: "merchant-onboarding-1",
      title: "Collect statements and void check",
      description: null,
      step_order: 3,
      completed_at: null,
      created_at: "2026-05-02T12:00:00.000Z",
    },
  ],
  signatureRequests: [
    {
      id: "signature-1",
      title: "Merchant processing agreement",
      recipient_name: "Sarah Mills",
      recipient_email: "sarah@buffaloauto.example",
      recipient_profile_id: null,
      related_entity_type: "merchant",
      related_entity_id: "merchant-2",
      document_id: null,
      provider: "mock",
      provider_request_id: "mock-demo-1",
      signing_url: "/documents?signature=mock-demo-1",
      status: "sent",
      metadata: {},
      created_by: "profile-agent-1",
      sent_at: "2026-05-06T08:00:00.000Z",
      completed_at: null,
      created_at: "2026-05-06T08:00:00.000Z",
      updated_at: "2026-05-06T08:00:00.000Z",
    },
  ],
  residualImportBatches: [],
  residuals: [
    {
      id: "residual-1",
      merchant_id: "merchant-3",
      agent_id: "agent-1",
      month: "2026-04-01",
      processing_volume: 126500,
      net_residual: 2580,
      agent_residual_amount: calculatePersonalResidual(2580),
      company_share: 1548,
      created_at: now,
    },
    {
      id: "residual-2",
      merchant_id: "merchant-5",
      agent_id: "agent-2",
      month: "2026-04-01",
      processing_volume: 91200,
      net_residual: 1760,
      agent_residual_amount: calculatePersonalResidual(1760),
      company_share: 1056,
      created_at: now,
    },
  ],
  processorConnections: [
    {
      id: "processor-connection-1",
      provider: "fiserv",
      display_name: "Fiserv CardConnect Portfolio",
      account_identifier: "MID ****1024",
      agent_profile_id: "profile-agent-1",
      created_by: "profile-agent-1",
      updated_by: "profile-agent-1",
      auth_type: "api_key",
      status: "connected",
      metadata: { environment: "sandbox", mode: "demo" },
      last_sync_at: now,
      last_tested_at: now,
      last_error: null,
      disconnected_at: null,
      created_at: now,
      updated_at: now,
    },
  ],
  processorSyncRuns: [
    {
      id: "processor-sync-1",
      connection_id: "processor-connection-1",
      status: "success",
      started_at: now,
      finished_at: now,
      records_processed: 12,
      error_message: null,
      metadata: { mode: "demo" },
    },
  ],
  agentPresence: [
    {
      profile_id: "profile-agent-1",
      status: "online",
      last_seen_at: now,
      current_path: "/dashboard",
      user_agent: "Demo browser",
      updated_at: now,
    },
  ],
  agentActivityLogs: [
    {
      id: "activity-1",
      profile_id: "profile-agent-1",
      actor_profile_id: "profile-agent-1",
      event_type: "integration.sync.success",
      event_source: "processor",
      provider: "fiserv",
      connection_id: "processor-connection-1",
      severity: "info",
      summary: "Fiserv demo connection synced sample portfolio activity.",
      metadata: { records_processed: 12 },
      ip_address: null,
      user_agent: null,
      created_at: now,
    },
  ],
  auditLogs: [],
  teams: [
    {
      id: "team-1",
      leader_agent_id: "agent-1",
      team_number: 1,
      created_at: now,
    },
  ],
  teamMembers: [
    {
      id: "team-member-1",
      team_id: "team-1",
      agent_id: "agent-2",
      sponsor_agent_id: "agent-1",
      active_recruit_status: false,
      active_status_date: null,
      created_at: now,
    },
    {
      id: "team-member-2",
      team_id: "team-1",
      agent_id: "agent-3",
      sponsor_agent_id: "agent-1",
      active_recruit_status: false,
      active_status_date: null,
      created_at: now,
    },
  ],
  compensationRule: {
    id: "rule-default",
    rule_name: "MerchantDesk Standard Agent Plan",
    base_residual_percentage: 40,
    minimum_processing_rate: 1.5,
    override_per_active_recruit: 0.25,
    max_override_per_team: 1,
    active_recruit_required_merchants: 2,
    active_recruit_required_processing_days: 90,
    created_at: now,
  },
  rolePermissions: defaultRolePermissions(),
  enterpriseSettings: enterpriseSettingDefaults,
  copilotMemories: [
    {
      id: "demo-memory-1",
      scope: "company",
      title: "MerchantDesk sales standard",
      content: "Confirm monthly volume, average ticket, current processor, owner contact, and statement availability before moving a merchant into underwriting.",
      entity_id: null,
      confidence: 0.9,
      source_type: "seed",
      source_id: null,
      metadata: {},
      created_by: null,
      created_at: now,
      updated_at: now,
    },
  ],
};

demoData.deals = demoData.merchants.map((merchant) => {
  const estimatedResidual = merchant.monthly_volume_estimate * (merchant.proposed_rate / 100) * 0.28;

  return {
    id: `deal-${merchant.id}`,
    merchant_id: merchant.id,
    agent_id: merchant.assigned_agent_id,
    stage: merchant.status,
    proposed_rate: merchant.proposed_rate,
    requires_management_approval: requiresManagementApproval(
      merchant.proposed_rate,
      demoData.compensationRule.minimum_processing_rate,
    ),
    approval_status: requiresManagementApproval(merchant.proposed_rate) ? "pending" : "not_required",
    estimated_monthly_volume: merchant.monthly_volume_estimate,
    estimated_residual: Math.round(estimatedResidual),
    close_probability: merchant.status === "processing" ? 100 : merchant.status === "underwriting" ? 68 : 42,
    expected_close_date: "2026-05-31",
    created_at: merchant.created_at,
    updated_at: merchant.updated_at,
  };
});
